theme: jekyll-theme-merlot
<!DOCTYPE html>
<html><text>Hi Mrs. Edwards thank you for being an AWSOME teacher. With all the Kahoots you invented. It was very fun being with you.
 I'll always remember you for your efforts in making each lesson enjoyable and educational. Thank you for being the best teacher a student could ever hope for.
</text>


<form action="index.html">
    <input type="submit" value="Go to homepage" />
</form>
</html>
